### ISSUE TITLE
parse $  on classes list?

### ISSUE THREAD

**Issue by liweijian** [aantron/lambda-soup#14]
According to [Readme](https://github.com/aantron/lambda-soup), we could get the text of some `class` by

```ocaml
"<p class='Hello'>World!</p>" |> parse $ ".Hello" |> R.leaf_text;;
- : string = "World!"
```

I was wondering how to get the text of a classes list? For example

```html
<p class='Hello Hey'>World!</p>"
```

**Comment by aantron** [comment]
Hi,

There are at least two options, depending on what you want.

1. [`attribute` or `R.attribute`](http://aantron.github.io/lambda-soup/#VALattribute) gives you the raw text of the `class` attribute:

    ```ocaml
    "<p class='Hello Hey'>World!</p>" |> parse $ "p" |> R.attribute "class";;
    - : string = "Hello Hey"
    ```

    The difference between the two is that `attribute` returns an option, so it will be `Some "Hello Hey"` above, and `None` if the attribute is absent; while `R.attribute` will throw an exception if the attribute is missing ([`R`](http://aantron.github.io/lambda-soup/#MODULER) stands for "require").

2. [`classes`](http://aantron.github.io/lambda-soup/#VALclasses) gives you the list of classes found in the `class` attribute:

    ```ocaml
    "<p class='Hello Hey'>World!</p>" |> parse $ "p" |> classes;;
    - : string list = ["Hello"; "Hey"]
    ```

**Comment by liweijian** [comment]
Thank you for your quick reply, actually what I want is to get the text of `p` element in a large html document.

Finally I found the answer

"<p class='Hello Hey'>World!</p>" |> parse $ ".Hello.Hey" |> R.leaf_text;;

**Comment by aantron** [comment]
Ah, yes, I see what you mean now :)

The only thing I would add is that if your `<p>` element can have child elements, you may want to do

```ocaml
(* ... *) $ ".Hello.Hey" |> texts |> String.concat ""
```

http://aantron.github.io/lambda-soup/#VALtexts

I'm actually not certain `leaf_text` is a good idea to even have in the API, but it's there...

**Comment by liweijian** [comment]
@aantron 

I am sorry to bother you again, I was wondering how may I using lambda soup to `getElementById()`?

```html
<div id='one'> 11</div><div id='two'> 22 </div>
```

For example, I want to get the text of some specific `id`?

**Comment by aantron** [comment]
No worries, this is not bothering :)

You can do it like this:

```ocaml
let soup = parse "<div id='one'> 11</div><div id='two'> 22 </div>") in
soup $ "#two" |> R.leaf_text
```

(I've split the code up into two lines, compared to before). This gives

```ocaml
- : string = " 22 "
```

In general, you may want to refer to the list of CSS selectors, whether [here](https://www.w3.org/TR/selectors/#selectors), or in your favorite CSS tutorial :)
