### ISSUE TITLE
opam install lambdasoup fails if $MAKEFLAGS is set 

### ISSUE THREAD

**Issue by jrochel** [aantron/lambda-soup#18]
See https://github.com/ocaml/dune/issues/638

**Comment by aantron** [comment]
This seems to have been a Jbuilder problem, [fixed in Jbuilder `1.0+beta19.1`](https://github.com/ocaml/dune/blob/master/CHANGES.md#10beta191-21032018).

**Comment by jrochel** [comment]
Alright. Should have been realised this by myself. Thanks.
