### ISSUE TITLE
element node to general node coercion

### ISSUE THREAD

**Issue by copy** [aantron/lambda-soup#20]
I'm trying to use the `Soup.create*` api to build up a lambdasoup object manually. This involves conditionally returning nodes created with either `Soup.create_element` or `Soup.create_text`. However, the types of the two are incompatible, so I would like to coerce the more specific type (`element node`) to the more general one (`general node`), i.e. a `coerce : 'a node -> general node` (or `element node -> general node`).

**Comment by aantron** [comment]
Thanks. I've also needed this function in my own work, and resorted to `Obj.magic`. There should now be `Soup.coerce` in `master` that does this. Would you like a speedy release to opam?

**Comment by copy** [comment]
> Would you like a speedy release to opam?

Whenever it's convenient.

**Comment by aantron** [comment]
@copy, I'm sure you got the emails already, but this is now in opam as `lambdasoup` 0.6.3.

**Comment by adrien-n** [comment]
BTW, I was using https://aantron.github.io/lambdasoup as a reference and it was only when I needed `coerce` that I realized how old the page was. You may want to either upload a new page or redirect to https://ocaml.org/p/lambdasoup/latest/doc/lambdasoup/Lambdasoup/index.html .
